version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_nest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nestdb
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/consulta.sql:/docker-entrypoint-initdb.d/consulta.sql:ro

volumes:
  mysql_data:
